blog_app/main/__init__.py
from flask import Blueprint

blog_app/main/views.py
# coding:utf-8
from flask import request, url_for, render_template, flash, redirect, session, abort, current_app
from blog_app.share.share_object import userClass, postClass, settingsClass, mediaClass
from blog_app.share.helper_functions import make_external
from blog_app.share.date_utils import get_cur_time
from pagination import Pagination
from blog_app.share.helper_functions import generate_csrf_token, login_required, extract_tags, single_keyword
import cgi
import mistune
import config
from flask import Blueprint
import json
from blog_app.share.log import logger

bp = Blueprint('main', __name__)


@bp.route('/', defaults={'page': 1})
@bp.route('/page-<int:page>')
def index(page):
    skip = (page - 1) * int(current_app.config['PER_PAGE'])
    posts = postClass.get_posts(int(current_app.config['PER_PAGE']), skip)
    count = postClass.get_total_count()
    pag = Pagination(page, current_app.config['PER_PAGE'], count)
    include_bd = config.INCLUDE_BD
    return render_template('index.html', posts=posts['data'], pagination=pag, include_bd=include_bd,
                           meta_title=current_app.config['BLOG_TITLE'])


@bp.route('/logout')
def logout():
    if userClass.logout():
        flash('You are logged out!', 'success')
    return redirect(url_for('.login'))


@bp.route('/login', methods=['GET', 'POST'])
def login():
    error = False
    error_type = 'validate'
    if request.method == 'POST':
        username = request.form.get('login-username')
        password = request.form.get('login-password')
        logger.critical(u"login blog IP %s time %s", request.remote_addr, get_cur_time())
        if not username or not password:
            error = True
        else:
            user_data = userClass.login(username.lower().strip(), password)
            if user_data['error']:
                error = True
                error_type = 'login'
                flash(user_data['error'], 'error')
            else:
                userClass.start_session(user_data['data'])
                flash('You are logged in!', 'success')
                return redirect(url_for('.posts'))
    else:
        if session.get('user'):
            return redirect(url_for('.posts'))

    return render_template('login.html',
                           meta_title='Login',
                           error=error,
                           error_type=error_type)


@bp.route('/search', methods=['GET', 'POST'])
def search():
    if request.method != 'POST':
        return redirect(url_for('.index'))

    query = request.form.get('query', None)
    if query:
        return redirect(url_for('.search_results', query=query))
    else:
        return redirect(url_for('.index'))


@bp.before_request
def csrf_protect():
    if request.method == "POST":
        token = session.pop('_csrf_token', None)
        if not token or token != request.form.get('_csrf_token'):
            abort(400)


@bp.before_request
def is_installed():
    current_app.config = settingsClass.get_config()
    current_app.jinja_env.globals['meta_description'] = current_app.config['BLOG_DESCRIPTION']
    if not session.get('installed', None):
        if url_for('static', filename='') not in request.path and request.path != url_for('main.install'):
            if not settingsClass.is_installed():
                return redirect(url_for('main.install'))


@bp.before_request
def set_globals():
    # current_app.jinja_env.globals['csrf_token'] = generate_csrf_token
    # current_app.jinja_env.globals['recent_posts'] = app.postClass.get_posts(10, 0)['data']
    # current_app.jinja_env.globals['tags'] = app.postClass.get_tags()['data']
    pass


@bp.route('/users')
@login_required()
def users_list():
    users = userClass.get_users()
    return render_template('users.html', users=users['data'], meta_title='Users')


@bp.route('/posts_list', defaults={'page': 1})
@bp.route('/posts_list/page-<int:page>')
@login_required()
def posts(page):
    session.pop('post-preview', None)
    skip = (page - 1) * int(current_app.config['PER_PAGE'])
    posts = postClass.get_posts(int(current_app.config['PER_PAGE']), skip)
    count = postClass.get_total_count()
    pag = Pagination(page, current_app.config['PER_PAGE'], count)

    if not posts['data']:
        abort(404)

    return render_template('posts.html', posts=posts['data'], pagination=pag, meta_title='Posts')


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html', meta_title='404'), 404


@bp.route('/newpost', methods=['GET', 'POST'])
@login_required()
def new_post():
    error = False
    error_type = 'validate'
    if request.method == 'POST':
        post_title = request.form.get('post-title').strip()
        post_full = request.form.get('post-full')
        post_keywords = request.form.get('post_keywords')

        if not post_title or not post_full:
            error = True
        else:
            tags = cgi.escape(request.form.get('post-tags'))
            tags_array = extract_tags(tags)

            post_short = request.form.get('post-short')

            post_keywords = single_keyword(post_keywords)

            if not post_short:
                post_short = post_full[:200]

            post_data = {'title': post_title,
                         'preview': post_short,
                         'post_keywords': post_keywords,
                         'body': post_full,
                         'tags': tags_array,
                         'author': session['user']['username']}

            post = postClass.validate_post_data(post_data)
            if request.form.get('post-preview') == '1':
                session['post-preview'] = post
                session[
                    'post-preview']['action'] = 'edit' if request.form.get('post-id') else 'add'
                if request.form.get('post-id'):
                    session[
                        'post-preview']['redirect'] = url_for('.post_edit', id=request.form.get('post-id'))
                else:
                    session['post-preview']['redirect'] = url_for('.new_post')
                return redirect(url_for('.post_preview'))
            else:
                session.pop('post-preview', None)

                if request.form.get('post-id'):
                    response = postClass.edit_post(
                        request.form['post-id'], post)
                    if not response['error']:
                        flash('Post updated!', 'success')
                    else:
                        flash(response['error'], 'error')
                    return redirect(url_for('.posts'))
                else:

                    post['view_count'] = 1

                    response = postClass.create_new_post(post)
                    if response['error']:
                        error = True
                        error_type = 'post'
                        flash(response['error'], 'error')
                    else:
                        flash('New post created!', 'success')
    else:
        if session.get('post-preview') and session['post-preview']['action'] == 'edit':
            session.pop('post-preview', None)
    return render_template('new_post.html',
                           meta_title='New post',
                           error=error,
                           error_type=error_type)


@bp.route('/install', methods=['GET', 'POST'])
def install():
    if session.get('installed', None):
        return redirect(url_for('.index'))

    error = False
    error_type = 'validate'
    if request.method == 'POST':
        user_error = False
        blog_error = False

        user_data = {
            '_id': request.form.get('user-id', None).lower().strip(),
            'email': request.form.get('user-email', None),
            'new_pass': request.form.get('user-new-password', None),
            'new_pass_again': request.form.get('user-new-password-again', None),
            'update': False
        }
        blog_data = {
            'title': request.form.get('blog-title', None),
            'description': request.form.get('blog-description', None),
            'per_page': request.form.get('blog-perpage', None),
            'text_search': request.form.get('blog-text-search', None)
        }
        blog_data['text_search'] = 1 if blog_data['text_search'] else 0

        for key, value in user_data.items():
            if not value and key != 'update':
                user_error = True
                break
        for key, value in blog_data.items():
            if not value and key != 'text_search' and key != 'description':
                blog_error = True
                break

        if user_error or blog_error:
            error = True
        else:
            install_result = settingsClass.install(blog_data, user_data)
            if install_result['error']:
                for i in install_result['error']:
                    if i is not None:
                        flash(i, 'error')
            else:
                session['installed'] = True
                flash('Successfully installed!', 'success')
                user_login = userClass.login(
                    user_data['_id'], user_data['new_pass'])
                if user_login['error']:
                    flash(user_login['error'], 'error')
                else:
                    userClass.start_session(user_login['data'])
                    flash('You are logged in!', 'success')
                    return redirect(url_for('.posts'))
    else:
        if settingsClass.is_installed():
            return redirect(url_for('.index'))

    return render_template('install.html',
                           default_settings=current_app.config,
                           error=error,
                           error_type=error_type,
                           meta_title='Install')


@bp.route('/tag/<tag>', defaults={'page': 1})
@bp.route('/tag/<tag>/page-<int:page>')
def posts_by_tag(tag, page):

blog_app/mg/__init__.py
from flask import Blueprint

bp = Blueprint('mg', __name__)
from . import views, model

blog_app/mg/views.py
# coding:utf-8
from flask import render_template, redirect, url_for, current_app
from flask import request, flash, session
from . import bp
from .model import UploadForm
from blog_app.application import set_mypic
from blog_app.share.share_object import mediaClass, userClass
from blog_app.share.helper_functions import login_required
from flask import Blueprint
from blog_app.share.log import logger, flask_log


@bp.route('/')
def index():
    # rst = (list(app.mediaClass.get_all()))
    # logger.error(u"ttt")
    #xx = 1/0
    # flask_log.fatal(u"ttt")
    from blog_app.share.share_object import *
    logger.error(postClass.get_all_tags())
    # rst = current_app.config.get('UPLOADED_MYPIC_DEST')
    rst = postClass.get_all_tags()
    return render_template('mg/index.html', rst=rst)


@bp.route('/upload_img', methods=('GET', 'POST'))
@login_required()
def upload_img():
    from datetime import datetime
    import time
    form = UploadForm()
    url = None
    # app.logger.warn(u"进入函数")
    # print 'jin'
    url_list = []
    if form.validate_on_submit():
        # 因为每个图片要写上 图片说明 所有一次只能上传一张图片
        # for filename in request.files.getlist('upload'):
        # filename = form.upload.data.filename
        # print u"图片开始保存"
        # return render_template('mg/upload_img.html', form=form, url_list=url_list)
        str_folder = str(datetime.today())[:7]
        filename = form.upload.data.filename[:-4] + "_" + str(time.time())[:11]
        # print u"图片开始保存"
        # 为啥这个都会报错。。。 打印个东西。。
        url_list.append(set_mypic.url(set_mypic.save(form.upload.data, folder=str_folder, name=filename)))

        # print u"图片已经保存"
        mediaClass.set_img_info(url_list[0], filename[:-1], request.form.get('explain'))

    return render_template('mg/upload_img.html', form=form, url_list=url_list)


@bp.route('/upload_img_info')
@login_required()
def get_img_info():
    rst_img_list = mediaClass.get_all()
    # app.logger.error(rst_img_list)
    return render_template('mg/img_info.html', rst_img_list=rst_img_list)


@bp.route('/add_user')
@login_required()
def add_user():
    gravatar_url = userClass.get_gravatar_link()
    return render_template('mg/add_user.html', gravatar_url=gravatar_url, meta_title='Add user')


@bp.route('/edit_user?id=<id>')
@login_required()
def edit_user(id):
    user = userClass.get_user(id)
    return render_template('mg/edit_user.html', user=user['data'], meta_title='Edit user')


@bp.route('/delete_user?id=<id>')
@login_required()
def delete_user(id):
    if id != session['user']['username']:
        user = userClass.delete_user(id)
        if user['error']:
            flash(user['error'], 'error')
        else:
            flash('User deleted!', 'success')
    return redirect(url_for('.users_list'))


@bp.route('/save_user', methods=['POST'])
@login_required()
def save_user():
    post_data = {
        '_id': request.form.get('user-id', None).lower().strip(),
        'email': request.form.get('user-email', None),
        'old_pass': request.form.get('user-old-password', None),
        'new_pass': request.form.get('user-new-password', None),
        'new_pass_again': request.form.get('user-new-password-again', None),
        'update': request.form.get('user-update', False)
    }
    if not post_data['email'] or not post_data['_id']:
        flash('Username and Email are required..', 'error')
        if post_data['update']:
            return redirect(url_for('.edit_user', id=post_data['_id']))
        else:
            return redirect(url_for('.add_user'))
    else:
        user = userClass.save_user(post_data)
        if user['error']:
            flash(user['error'], 'error')
            if post_data['update']:
                return redirect(url_for('.edit_user', id=post_data['_id']))
            else:
                return redirect(url_for('.add_user'))
        else:
            message = 'User updated!' if post_data['update'] else 'User added!'
            flash(message, 'success')
    return redirect(url_for('.edit_user', id=post_data['_id']))

blog_app/templates/baidu_zz.html
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>

blog_app/templates/edit_post.html
{%- extends 'index.html' -%}
{%- block body -%}
	{% if session.get('post-preview', None) %}
		{% set post_title = session['post-preview'].get('title', None) %}
		{% set post_preview = session['post-preview'].get('preview', None) %}
		{% set post_body = session['post-preview'].get('body', None) %}
		{% set tags = session['post-preview'].get('tags', None) %}
		{% if tags %}
			{% set post_tags = ','.join(tags) %}
		{% endif %}
	{% else %}
		{% set post_title = post.get('title') %}
		{% set post_preview = post.get('preview') %}
		{% set post_body = post.get('body') %}
		{% set post_tags = post.get('tags') %}
	{% endif %}
	<div class="post clearfix">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>Edit Post</h1>
				</div>
				<div class="content">
					{%- with messages = get_flashed_messages(with_categories=True) -%}
						{%- if messages -%}
							{%- for category, message in messages -%}
								<div class="response">
									<span class="message {{ category }}">{%- if category == 'success' -%}✔{%- endif -%}&nbsp;{{ message }}</span>
								</div>
							{%- endfor -%}
						{%- endif -%}
					{%- endwith -%}
					<form id="post-form" role="form" method="post" action="{{ url_for('main.new_post') }}">
						<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
							{%- if error and error_type == 'validate' -%}
								<label class="control-label" for="post-title">Required field</label>
							{%- endif -%}
						    <input type="text" class="form-control" name="post-title" id="post-title" placeholder="Post Title" required value="{{ post_title | safe }}">
					    </div>
                        <div class="form-group">
                            <span>keywords 方便爬虫收入</span>
						    <textarea id="post_keywords" name="post_keywords" class="form-control" rows="1" placeholder="Short Text">{{ post_keywords | safe }}</textarea>
					    </div>

						<div class="form-group">
						    <textarea id="post-short" name="post-short" class="form-control" rows="3" placeholder="Short Text">{{ post_preview | safe }}</textarea>
					    </div>
						<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
							{%- if error and error_type == 'validate' -%}
								<label class="control-label" for="post-full">Required field</label>
							{%- endif -%}
						    <textarea id="post-full" name="post-full" class="form-control" rows="20" placeholder="Full Text" required>{{ post_body | safe }}</textarea>
					    </div>
                        <div class="form-group">
                            <p>已存在的标签</p>
                                <span>{{ tags_list | safe}}</span>
                        </div>
						<div class="form-group">
						    <label for="post-tags">Tags</label>
						    <input type="text" name="post-tags" class="form-control" id="post-tags" placeholder="Comma separated" value="{{ post_tags }}">
					    </div>
						<div class="form-group">
							<input type="hidden" name="post-preview" id="preview">
							<input type="hidden" name="post-id" value="{{ post['_id'] }}">
							<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
						    <input id="post-submit" type="submit" class="btn btn-primary" value="Submit">
							<input id="post-preview" type="submit" class="btn" value="Preview">
					    </div>
					</form>
				</div>
			</div>
		</div>
	</div>
{%- endblock -%}
{%- block scripts -%}
	<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script src="{{ url_for('static', filename='js/a-tools.js') }}"></script>
	<script src="{{ url_for('static', filename='js/showdown.js') }}"></script>
	<script src="{{ url_for('static', filename='js/mdmagick.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
{%- endblock -%}

blog_app/templates/footer.html
<footer>
	<div class="container">
		<p>Copyright © 2017 版权声明 &nbsp; 
			<a target="_blank" href="http://www.miitbeian.gov.cn/state/outPortal/loginPortal.action">粤ICP备16128938号 </a>
		</p>
	</div>
</footer>

blog_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
	{%- block head -%}{%- include 'head.html' -%}{%- endblock -%}
	<body>
		<div id="wrapper">
			{%- block nav -%}{%- include 'nav.html' -%}{%- endblock -%}
			<div class="container">
				{%- block body -%}
					{%- if posts -%}
						{%- for post in posts -%}
							<div class="post clearfix">
								<div class="row">
									<div class="col-lg-8">
										<div class="page-header">
											<h2><a href="{{ url_for('main.single_post', permalink=post['permalink']) }}">{{ post['title'] | safe }}</a></h2>
											<p><span class="icon-time">&nbsp;</span><i>Posted on {{ post['date']|formatdate }} by {{ post['author'] }}</i>
                                                {% if post.get('update') %}
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="fa fa-refresh fa-fw">&nbsp;</span><i>Update:{{ post.get('update')|formatdate }}</i>
                                                {% endif %}
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="fa fa-fire fa-fw">&nbsp;{{post.get('view_count')}}</span>
                                            </p>
										</div>
										<div class="content no-lightbox">
											{%- if post['preview'] -%}
												{{ post['preview']|markdown }}
											{%- else -%}
												{{ post['body']|markdown }}
											{%- endif -%}
										</div>
                                        {%- if post['tags'] -%}
										<div class="infopanel">
											<div class="tags">

												<li class="fa fa-tag fa-fw" title="tags"></li>

													{%- for tag in post['tags'] -%}
														&nbsp;<a href="{{ url_for('main.posts_by_tag', tag=tag) }}">{{ tag }}</a>
													{%- endfor -%}

											</div>
										</div>
                                       {%- endif -%}
									</div>
								</div>
							</div>
						{%- endfor -%}
					{% else %}
						<div class="post clearfix">
							<div class="row">
								<div class="col-lg-8">
									<div class="page-header">
										<h1>Posts not found..</h1>
									</div>
								</div>
							</div>
						</div>
					{%- endif -%}
					{%- include 'sidebar.html' -%}
				{%- endblock -%}
				{% if pagination and pagination.pages > 1 %}
					<div class="pagination-wrap">
						<ul class="pagination">
						  {% for page in pagination.iter_pages() %}
						    {% if page %}
						        <li {% if page == pagination.page %}class="active"{% endif %}><a href="{{ url_for_other_page(page) }}">{{ page }}</a></li>
						    {% else %}
						      <li><span class=ellipsis>…</span></li>
						    {% endif %}
						  {% endfor %}
						  {% if pagination.has_next %}
						    <li><a href="{{ url_for_other_page(pagination.page + 1)
						      }}">&raquo;</a></li>
						  {% endif %}
						</ul>
					</div>
				{% endif %}
			</div>
		</div>
		{%- include 'footer.html' -%}
		{%- block scripts -%}
			<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
			<script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
            {%- block additional_js -%}{%- endblock -%}
			<script src="{{ url_for('static', filename='js/main.js') }}"></script>
		{%- endblock -%}
        {% if include_bd %}
            {%- include 'baidu_zz.html' -%}
        {% endif %}
    </body>
</html>

blog_app/templates/nav.html
<div class="navbar navbar-default navbar-fixed-top">
	<div class="navbar-header">
		<ul class="nav navbar-nav">
			<li><a href="{{ url_for('main.index') }}" class="navbar-brand">Home</a></li>
		{% if session.user %}
			<li><a href="{{ url_for('main.logout') }}">Logout</a></li>
		{% else %}
			<li><a href="{{ url_for('main.login') }}">Login</a></li>
		{% endif %}
		</ul>

		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<div class="navbar-collapse collapse" id="navbar-main">
		<ul class="nav navbar-nav">
{#			<li><a href="{{ url_for('recent_feed') }}" class="icon-rss"></a></li>#}
		{% if session.user %}
			<li><a href="{{ url_for('main.users_list') }}">Users</a></li>
			<li><a href="{{ url_for('main.posts') }}">Posts</a></li>
			<li><a href="{{ url_for('main.new_post') }}">New post</a></li>
			<li><a href="{{ url_for('main.blog_settings') }}">Settings</a></li>
            <li><a href="{{ url_for('main.manage_trifles') }}">mg</a></li>
		{% endif %}
		</ul>
		<form class="navbar-form navbar-right search-form" method="post" action="{{ url_for('main.search') }}">
            <input type="text" name="query" class="form-control col-lg-8" placeholder="Search">
			<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
		</form>
	</div>
</div>

blog_app/templates/new_post.html
{%- extends 'index.html' -%}
{%- block body -%}
	{% if session.get('post-preview') %}
		{% set post_title = session['post-preview'].get('title', None) %}
		{% set post_preview = session['post-preview'].get('preview', None) %}
		{% set post_body = session['post-preview'].get('body', None) %}
		{% set post_tags = session['post-preview'].get('tags', None) %}
	{% else %}
		{% set post_title = '' %}
		{% set post_preview = '' %}
		{% set post_body = '' %}
		{% set post_tags = '' %}
	{% endif %}

	<div class="post clearfix">
		<div class="row">
			<div class="col-lg-8">
				<div class="page-header">
					<h1>New post</h1>
				</div>
				<div class="content">
					{%- with messages = get_flashed_messages(with_categories=True) -%}
						{%- if messages -%}
							{%- for category, message in messages -%}
								<div class="response">
									<span class="message {{ category }}">{%- if category == 'success' -%}✔{%- endif -%}&nbsp;{{ message }}</span>
								</div>
							{%- endfor -%}
						{%- endif -%}
					{%- endwith -%}
					<form id="post-form" role="form" method="post" action="{{ url_for('main.new_post') }}">
						<div class="form-group {% if error and error_type == 'validate' %} has-error{% endif %}">
							{%- if error and error_type == 'validate' -%}
								<label class="control-label" for="post-title">Required field</label>
							{%- endif -%}
						    <input type="text" class="form-control" name="post-title" id="post-title" placeholder="Post Title" value="{{ post_title | safe }}" required>
					    </div>
                        <div class="form-group">
                            <span>keywords 方便爬虫收入</span>
						    <textarea id="post_keywords" name="post_keywords" class="form-control" rows="1" placeholder="Short Text">{{ post_keywords | safe }}</textarea>
					    </div>
						<div class="form-group">
                            <span>keywords 简单的描述</span>
						    <textarea id="post-short" name="post-short" class="form-control" rows="3" placeholder="Short Text">{{ post_preview | safe }}</textarea>
					    </div>
						<div class="form-group {% if error and error_type == 'validate' %} has-error{% endif %}">
							{%- if error and error_type == 'validate' -%}
								<label class="control-label" for="post-full">Required field</label>
							{%- endif -%}
						    <textarea id="post-full" name="post-full" class="form-control" rows="6" placeholder="Full Text" required>{{ post_body | safe }}</textarea>
					    </div>
						<div class="form-group">
						    <label for="post-tags">Tags</label>
						    <input type="text" name="post-tags" class="form-control" id="post-tags" placeholder="Comma separated" value="{{ ','.join(post_tags) }}">
					    </div>
						<div class="form-group">
							<input type="hidden" name="post-preview" id="preview">
							<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
						    <input id="post-submit" type="submit" class="btn btn-primary" value="Submit">
							<input id="post-preview" type="submit" class="btn" value="Preview">
					    </div>
					</form>
				</div>
			</div>
		</div>
	</div>
{%- endblock -%}
{%- block scripts -%}
	<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script src="{{ url_for('static', filename='js/a-tools.js') }}"></script>
	<script src="{{ url_for('static', filename='js/showdown.js') }}"></script>
	<script src="{{ url_for('static', filename='js/mdmagick.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
{%- endblock -%}

blog_app/templates/sidebar.html
{%- if recent_posts -%}
<div class="col-lg-3 visible-lg sidebar">
    <h2>Recent articles</h2>
    <hr>
    <ul>
    {% for post in recent_posts %}
        <li><a href="{{ url_for('main.single_post', permalink=post['permalink']) }}">{{ post['title'] | safe }}</a></li>
    {% endfor %}
    </ul>
    {%- if tags -%}
    <h2>Top tags</h2>
    <hr>
    <ul>
    {% for tag in tags %}
        <li><a href="{{ url_for('main.posts_by_tag', page=1, tag=tag['title']) }}">{{ tag['title'] }} <sup class="badge">{{ tag['count'] }}</sup></a></li>
    {% endfor %}
    </ul>
    {%- endif -%}
</div>
{%- endif -%}

blog_app/templates/test_use.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {{ tt }}
</head>
<body>

</body>
</html>

blog_app/templates/users.html
{%- extends 'index.html' -%}
{%- block body -%}
	<div class="post">
		<div class="row">
			<div class="col-lg-12">
				{%- if users -%}
					<div class="page-header">
						<h1>Users</h1>
					</div>
					<div class="content">
						{%- with messages = get_flashed_messages(with_categories=True) -%}
		                    {%- if messages -%}
		                        {%- for category, message in messages -%}
		                            <div class="response">
		                                <span class="message {{ category }}">{%- if category == 'success' -%}✔{%- endif -%}&nbsp;{{ message }}</span>
		                            </div>
		                        {%- endfor -%}
		                    {%- endif -%}
		                {%- endwith -%}
						<a href="{{ url_for('mg.add_user') }}" class="response btn btn-primary">Add User</a>
						<table class="table table-striped">
							<tr>
								<th>Username</th>
								<th>Email</th>
								<th>Registration Date</th>
								<th>Action</th>
							</tr>
							{%- for user in users -%}
							<tr>
								<td><a title="Username" href="{{ url_for('mg.edit_user', id=user['id']) }}" data-target="_blank">{{ user['id'] }}</a></td>
								<td>{{ user['email'] }}</td>
								<td>{{ user['date'] |formatdate }}</td>
								<td><a title="Edit" href="{{ url_for('mg.edit_user', id=user['id']) }}" class="icon-edit-sign bigger icon"></a>{%- if user['id'] != session['user']['username'] -%}&nbsp;&nbsp;<a title="Delete" href="{{ url_for('delete_user', id=user['id']) }}" class="icon-remove-sign bigger icon"></a>{%- endif -%}</td>
							</tr>
							{%- endfor -%}
						</table>
					</div>
				{%- endif -%}
		    </div>
		</div>
	</div>
{%- endblock -%}