app/mg/__init__.py
from flask import Blueprint

mg = Blueprint('mg',__name__)

from . import views, model

app/mg/views.py
# coding:utf-8
from flask import render_template, redirect, url_for, current_app
from flask import request, flash, session
from config import UPDATE_INFO
from . import mg as mg_bp
from .model import UploadForm
from app import set_mypic
from app import mediaClass
import app
from app.share.helper_functions import login_required


@mg_bp.route('/')
def index():
    # rst = (list(app.mediaClass.get_all()))
    rst = current_app.config.get('UPLOADED_MYPIC_DEST')
    return render_template('mg/index.html', rst=rst)


@mg_bp.route('/upload_img', methods=('GET', 'POST'))
@login_required()
def upload_img():
    from datetime import datetime
    import time
    form = UploadForm()
    url = None
    # app.logger.warn(u"进入函数")
    # print 'jin'
    url_list = []
    if form.validate_on_submit():
        # 因为每个图片要写上 图片说明 所有一次只能上传一张图片
        # for filename in request.files.getlist('upload'):
        # filename = form.upload.data.filename
        # print u"图片开始保存"
        # return render_template('mg/upload_img.html', form=form, url_list=url_list)
        str_folder = str(datetime.today())[:7]
        filename = form.upload.data.filename[:-4] + "_" + str(time.time())[:11]
        # print u"图片开始保存"
        # 为啥这个都会报错。。。 打印个东西。。
        url_list.append(set_mypic.url(set_mypic.save(form.upload.data, folder=str_folder, name=filename)))

        # print u"图片已经保存"
        app.mediaClass.set_img_info(url_list[0], filename[:-1], request.form.get('explain'))

    return render_template('mg/upload_img.html', form=form, url_list=url_list)


@mg_bp.route('/upload_img_info')
@login_required()
def get_img_info():
    rst_img_list = mediaClass.get_all()
    # app.logger.error(rst_img_list)
    return render_template('mg/img_info.html', rst_img_list=rst_img_list)


@mg_bp.route('/add_user')
@login_required()
def add_user():
    gravatar_url = app.userClass.get_gravatar_link()
    return render_template('mg/add_user.html', gravatar_url=gravatar_url, meta_title='Add user')


@mg_bp.route('/edit_user?id=<id>')
@login_required()
def edit_user(id):
    user = app.userClass.get_user(id)
    return render_template('mg/edit_user.html', user=user['data'], meta_title='Edit user')


@mg_bp.route('/delete_user?id=<id>')
@login_required()
def delete_user(id):
    if id != session['user']['username']:
        user = app.userClass.delete_user(id)
        if user['error']:
            flash(user['error'], 'error')
        else:
            flash('User deleted!', 'success')
    return redirect(url_for('.users_list'))


@mg_bp.route('/save_user', methods=['POST'])
@login_required()
def save_user():
    post_data = {
        '_id': request.form.get('user-id', None).lower().strip(),
        'email': request.form.get('user-email', None),
        'old_pass': request.form.get('user-old-password', None),
        'new_pass': request.form.get('user-new-password', None),
        'new_pass_again': request.form.get('user-new-password-again', None),
        'update': request.form.get('user-update', False)
    }
    if not post_data['email'] or not post_data['_id']:
        flash('Username and Email are required..', 'error')
        if post_data['update']:
            return redirect(url_for('.edit_user', id=post_data['_id']))
        else:
            return redirect(url_for('.add_user'))
    else:
        user = app.userClass.save_user(post_data)
        if user['error']:
            flash(user['error'], 'error')
            if post_data['update']:
                return redirect(url_for('.edit_user', id=post_data['_id']))
            else:
                return redirect(url_for('.add_user'))
        else:
            message = 'User updated!' if post_data['update'] else 'User added!'
            flash(message, 'success')
    return redirect(url_for('.edit_user', id=post_data['_id']))

blog_app/main/__init__.py
from flask import Blueprint

blog_app/main/views.py
# coding:utf-8
from flask import request, url_for, render_template, flash, redirect, session, abort, current_app
from blog_app.share.share_object import userClass, postClass, settingsClass, mediaClass
from blog_app.share.helper_functions import make_external
from blog_app.share.date_utils import get_cur_time
from pagination import Pagination
from blog_app.share.helper_functions import generate_csrf_token, login_required, extract_tags, single_keyword
import cgi
import mistune
import config
from flask import Blueprint
import json
from blog_app.share.log import logger

bp = Blueprint('main', __name__)


@bp.route('/', defaults={'page': 1})
@bp.route('/page-<int:page>')
def index(page):
    skip = (page - 1) * int(current_app.config['PER_PAGE'])
    posts = postClass.get_posts(int(current_app.config['PER_PAGE']), skip)
    count = postClass.get_total_count()
    pag = Pagination(page, current_app.config['PER_PAGE'], count)
    include_bd = config.INCLUDE_BD
    return render_template('index.html', posts=posts['data'], pagination=pag, include_bd=include_bd,
                           meta_title=current_app.config['BLOG_TITLE'])


@bp.route('/logout')
def logout():
    if userClass.logout():
        flash('You are logged out!', 'success')
    return redirect(url_for('.login'))


@bp.route('/login', methods=['GET', 'POST'])
def login():
    error = False
    error_type = 'validate'
    if request.method == 'POST':
        username = request.form.get('login-username')
        password = request.form.get('login-password')
        logger.critical(u"login blog IP %s time %s", request.remote_addr, get_cur_time())
        if not username or not password:
            error = True
        else:
            user_data = userClass.login(username.lower().strip(), password)
            if user_data['error']:
                error = True
                error_type = 'login'
                flash(user_data['error'], 'error')
            else:
                userClass.start_session(user_data['data'])
                flash('You are logged in!', 'success')
                return redirect(url_for('.posts'))
    else:
        if session.get('user'):
            return redirect(url_for('.posts'))

    return render_template('login.html',
                           meta_title='Login',
                           error=error,
                           error_type=error_type)


@bp.route('/search', methods=['GET', 'POST'])
def search():
    if request.method != 'POST':
        return redirect(url_for('.index'))

    query = request.form.get('query', None)
    if query:
        return redirect(url_for('.search_results', query=query))
    else:
        return redirect(url_for('.index'))


@bp.before_request
def csrf_protect():
    if request.method == "POST":
        token = session.pop('_csrf_token', None)
        if not token or token != request.form.get('_csrf_token'):
            abort(400)


@bp.before_request
def is_installed():
    current_app.config = settingsClass.get_config()
    current_app.jinja_env.globals['meta_description'] = current_app.config['BLOG_DESCRIPTION']
    if not session.get('installed', None):
        if url_for('static', filename='') not in request.path and request.path != url_for('main.install'):
            if not settingsClass.is_installed():
                return redirect(url_for('main.install'))


@bp.before_request
def set_globals():
    # current_app.jinja_env.globals['csrf_token'] = generate_csrf_token
    # current_app.jinja_env.globals['recent_posts'] = app.postClass.get_posts(10, 0)['data']
    # current_app.jinja_env.globals['tags'] = app.postClass.get_tags()['data']
    pass


@bp.route('/users')
@login_required()
def users_list():
    users = userClass.get_users()
    return render_template('users.html', users=users['data'], meta_title='Users')


@bp.route('/posts_list', defaults={'page': 1})
@bp.route('/posts_list/page-<int:page>')
@login_required()
def posts(page):
    session.pop('post-preview', None)
    skip = (page - 1) * int(current_app.config['PER_PAGE'])
    posts = postClass.get_posts(int(current_app.config['PER_PAGE']), skip)
    count = postClass.get_total_count()
    pag = Pagination(page, current_app.config['PER_PAGE'], count)

    if not posts['data']:
        abort(404)

    return render_template('posts.html', posts=posts['data'], pagination=pag, meta_title='Posts')


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html', meta_title='404'), 404


@bp.route('/newpost', methods=['GET', 'POST'])
@login_required()
def new_post():
    error = False
    error_type = 'validate'
    if request.method == 'POST':
        post_title = request.form.get('post-title').strip()
        post_full = request.form.get('post-full')
        post_keywords = request.form.get('post_keywords')

        if not post_title or not post_full:
            error = True
        else:
            tags = cgi.escape(request.form.get('post-tags'))
            tags_array = extract_tags(tags)

            post_short = request.form.get('post-short')

            post_keywords = single_keyword(post_keywords)

            if not post_short:
                post_short = post_full[:200]

            post_data = {'title': post_title,
                         'preview': post_short,
                         'post_keywords': post_keywords,
                         'body': post_full,
                         'tags': tags_array,
                         'author': session['user']['username']}

            post = postClass.validate_post_data(post_data)
            if request.form.get('post-preview') == '1':
                session['post-preview'] = post
                session[
                    'post-preview']['action'] = 'edit' if request.form.get('post-id') else 'add'
                if request.form.get('post-id'):
                    session[
                        'post-preview']['redirect'] = url_for('.post_edit', id=request.form.get('post-id'))
                else:
                    session['post-preview']['redirect'] = url_for('.new_post')
                return redirect(url_for('.post_preview'))
            else:
                session.pop('post-preview', None)

                if request.form.get('post-id'):
                    response = postClass.edit_post(
                        request.form['post-id'], post)
                    if not response['error']:
                        flash('Post updated!', 'success')
                    else:
                        flash(response['error'], 'error')
                    return redirect(url_for('.posts'))
                else:

                    post['view_count'] = 1

                    response = postClass.create_new_post(post)
                    if response['error']:
                        error = True
                        error_type = 'post'
                        flash(response['error'], 'error')
                    else:
                        flash('New post created!', 'success')
    else:
        if session.get('post-preview') and session['post-preview']['action'] == 'edit':
            session.pop('post-preview', None)
    return render_template('new_post.html',
                           meta_title='New post',
                           error=error,
                           error_type=error_type)


@bp.route('/install', methods=['GET', 'POST'])
def install():
    if session.get('installed', None):
        return redirect(url_for('.index'))

    error = False
    error_type = 'validate'
    if request.method == 'POST':
        user_error = False
        blog_error = False

        user_data = {
            '_id': request.form.get('user-id', None).lower().strip(),
            'email': request.form.get('user-email', None),
            'new_pass': request.form.get('user-new-password', None),
            'new_pass_again': request.form.get('user-new-password-again', None),
            'update': False
        }
        blog_data = {
            'title': request.form.get('blog-title', None),
            'description': request.form.get('blog-description', None),
            'per_page': request.form.get('blog-perpage', None),
            'text_search': request.form.get('blog-text-search', None)
        }
        blog_data['text_search'] = 1 if blog_data['text_search'] else 0

        for key, value in user_data.items():
            if not value and key != 'update':
                user_error = True
                break
        for key, value in blog_data.items():
            if not value and key != 'text_search' and key != 'description':
                blog_error = True
                break

        if user_error or blog_error:
            error = True
        else:
            install_result = settingsClass.install(blog_data, user_data)
            if install_result['error']:
                for i in install_result['error']:
                    if i is not None:
                        flash(i, 'error')
            else:
                session['installed'] = True
                flash('Successfully installed!', 'success')
                user_login = userClass.login(
                    user_data['_id'], user_data['new_pass'])
                if user_login['error']:
                    flash(user_login['error'], 'error')
                else:
                    userClass.start_session(user_login['data'])
                    flash('You are logged in!', 'success')
                    return redirect(url_for('.posts'))
    else:
        if settingsClass.is_installed():
            return redirect(url_for('.index'))

    return render_template('install.html',
                           default_settings=current_app.config,
                           error=error,
                           error_type=error_type,
                           meta_title='Install')


@bp.route('/tag/<tag>', defaults={'page': 1})
@bp.route('/tag/<tag>/page-<int:page>')
def posts_by_tag(tag, page):

blog_app/mg/__init__.py
from flask import Blueprint

bp = Blueprint('mg', __name__)
from . import views, model

blog_app/templates/mg/add_user.html
{%- extends 'index.html' -%}
{%- block body -%}
	<div class="post clearfix">
		<div class="row">
			<div class="col-lg-8">
				<div class="page-header">
					<h1>Add User</h1>
				</div>
				<div class="content">
					{%- with messages = get_flashed_messages(with_categories=True) -%}
						{%- if messages -%}
							{%- for category, message in messages -%}
								<div class="response">
									<span class="message {{ category }}">{%- if category == 'success' -%}✔{%- endif -%}&nbsp;{{ message }}</span>
								</div>
							{%- endfor -%}
						{%- endif -%}
					{%- endwith -%}
					<form class="form-user" role="form" method="post" action="{{ url_for('mg.save_user') }}">
						<div class="photo-user">
							<img src="{{ gravatar_url }}" class="img-circle">
						</div>
						<div>
							<fieldset>
							<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
								{%- if error and error_type == 'validate' -%}
									<label class="control-label" for="user-id">Required field</label>
								{%- endif -%}
							    <input type="text" class="form-control" name="user-id" id="user-id" placeholder="Username" value="" required autocomplete="off">
							</div>
							<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
								{%- if error and error_type == 'validate' -%}
									<label class="control-label" for="user-email">Required field</label>
								{%- endif -%}
							    <input type="email" class="form-control" name="user-email" id="user-email" placeholder="Email" value="" required autocomplete="off">
							</div>
						</fieldset>
						<fieldset>
						<legend>Password section</legend>
							<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
								{%- if error and error_type == 'validate' -%}
									<label class="control-label" for="user-new-password">Required field</label>
								{%- endif -%}
							    <input type="password" class="form-control" name="user-new-password" id="user-new-password" placeholder="Password" value="" required autocomplete="off">
							</div>
							<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
								{%- if error and error_type == 'validate' -%}
									<label class="control-label" for="user-new-password-again">Required field</label>
								{%- endif -%}
							    <input type="password" class="form-control" name="user-new-password-again" id="user-new-password-again" placeholder="Repeat Password" value="" required autocomplete="off">
							</div>
						</fieldset>
						<div class="form-group">
							<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
						    <input id="post-submit" type="submit" class="btn btn-primary" value="Submit">
					    </div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{%- endblock -%}

blog_app/templates/mg/edit_user.html
{%- extends 'index.html' -%}
{%- block body -%}
	<div class="post clearfix">
		<div class="row">
			<div class="col-lg-8">
				<div class="page-header">
					<h1>Edit user</h1>
				</div>
				<div class="content">
					{%- with messages = get_flashed_messages(with_categories=True) -%}
						{%- if messages -%}
							{%- for category, message in messages -%}
								<div class="response">
									<span class="message {{ category }}">{%- if category == 'success' -%}✔{%- endif -%}&nbsp;{{ message }}</span>
								</div>
							{%- endfor -%}
						{%- endif -%}
					{%- endwith -%}
					{%- if user -%}
						<form class="form-user" role="form" method="post" action="{{ url_for('mg.save_user') }}">
							<div class="photo-user">
								<img src="{{ user['gravatar_url'] }}" class="img-circle">
							</div>
							<div>
								<fieldset>
									<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
										{%- if error and error_type == 'validate' -%}
											<label class="control-label" for="user-username">Required field</label>
										{%- endif -%}
									    <input type="text" class="form-control" name="user-username" id="user-username" placeholder="Username" value="{{ user['_id'] }}" required autocomplete="off" disabled>
									</div>
									<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
										{%- if error and error_type == 'validate' -%}
											<label class="control-label" for="user-email">Required field</label>
										{%- endif -%}
									    <input type="email" class="form-control" name="user-email" id="user-email" placeholder="Email" value="{{ user['email'] }}" required autocomplete="off">
									</div>
								</fieldset>
								<fieldset>
								<legend>Password section</legend>
									<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
										{%- if error and error_type == 'validate' -%}
											<label class="control-label" for="user-old-password">Required field</label>
										{%- endif -%}
									    <input type="password" class="form-control" name="user-old-password" id="user-old-password" placeholder="Current Password" autocomplete="off">
									</div>
									<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
										{%- if error and error_type == 'validate' -%}
											<label class="control-label" for="user-new-password">Required field</label>
										{%- endif -%}
									    <input type="password" class="form-control" name="user-new-password" id="user-new-password" placeholder="New Password" autocomplete="off">
									</div>
									<div class="form-group {% if error and error_type == 'validate' %}has-error{% endif %}">
										{%- if error and error_type == 'validate' -%}
											<label class="control-label" for="user-new-password-again">Required field</label>
										{%- endif -%}
									    <input type="password" class="form-control" name="user-new-password-again" id="user-new-password-again" placeholder="New Password Repeat" autocomplete="off">
									</div>
								</fieldset>
								<div class="form-group">
									<input name="user-id" type="hidden" value="{{ user['_id'] }}">
									<input name="user-update" type="hidden" value="1">
									<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
								    <input id="post-submit" type="submit" class="btn btn-primary" value="Submit">
							    </div>
							</div>
						</form>
					{%- endif -%}
				</div>
			</div>
		</div>
	</div>
{%- endblock -%}

blog_app/templates/mg/img_info.html
<!DOCTYPE html>
<html lang="en">
{%- block head -%}{%- include 'head.html' -%}{%- endblock -%}
<body>
<div id="wrapper">
    {%- block nav -%}{%- include 'nav.html' -%}{%- endblock -%}
    <div >
        <div class="post clearfix">
            <div class="row">
                <div>
                    <table class="table table-hover" style="text-align:center;">
                        <tr>
                            <td>时间</td>
                            <td>状态</td>
                            <td>url</td>
                            <td>文件名</td>
                            <td>描述</td>
                            <td >显示</td>
                        </tr>
                        {% for item in rst_img_list %}
                            <tr>
                                <td>{{ item.optime }}</td>
                                <td>{{ item.status }}</td>
                                <td>{{ item.address }}</td>
                                <td>{{ item.filename }}</td>
                                <td>{{ item.describe }}</td>
                                <td style="width: 200px;height: 300px"><img src="{{ item.address }}"></td>
                            </tr>

                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
{%- include 'footer.html' -%}
		{%- block scripts -%}
			<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
			<script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
            {%- block additional_js -%}{%- endblock -%}
			<script src="{{ url_for('static', filename='js/main.js') }}"></script>
		{%- endblock -%}
	</body>
</html>

blog_app/templates/mg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
ok
{{ rst }}
</body>
</html>

blog_app/templates/mg/upload_img.html
 {% import "bootstrap/wtf.html" as wtf %}
{%- extends 'index.html' -%}
{%- block body -%}

    {% block page_content %}
        <div class="row" style="position: absolute;top: 60px">
			<div class="col-lg-12">
            <div id="uploadPreview">
            </div>
{#            <h4>uploaded: {% if url %} {{ url }}{% endif %}</h4>#}
            {#     <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">#}
            {#     {{ wtf.quick_form(form, enctype="multipart/form-data") }}#}

            <form method="POST" enctype="multipart/form-data" onsubmit="return check_fun();">
                {{ form.csrf_token }}
                <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
                {{ form.upload }} <br/>
                {{ form.explain }} <br/>
                {{ form.submit }}

            </form>
            <div class="col-lg-6">
                {% for url in url_list %}
                <ul>
                    <li><div>
                        <span>{{ url }}</span>
                        <img style="width:200px;height: 200px" src="{{ url }}">
                    </div></li>
                </ul>
                {% endfor %}
            </div>
           </div>
		</div>
    {% endblock page_content %}

	{#<div class="post">
		<div class="row">
			<div class="col-lg-12">
                <div>
                    <img id="uploadPreview" src="">
                    <form action={{ url_for('img_upload') }} method="post">
                        <input type="file" name="imgupload" id="imgupload">
                        <input type="submit" value="Submit">
                    </form>
                </div>
		    </div>
		</div>
	</div>#}
{%- endblock -%}

{%- block scripts -%}
    {{ super() }}

    <script>

        function check_fun() {
            var exp = document.getElementById('explain');
            if(exp.value.length >= 8){
                return true;
            }else{
                alert('请输入说明或者是文字不够长');
                return false;
            }
        }

        if (typeof FileReader === 'undefined') {
            alert("抱歉，你的浏览器不支持 FileReader");
        }
        $("#upload").change(function (e) {
            for (var i = 0; i < e.target.files.length; i++) {
                var file = e.target.files.item(i);
                var freader = new FileReader();
                freader.readAsDataURL(file);
                freader.onload = function (e) {
                    var src = e.target.result;
                    //console.log(e.target);
                    //$("#uploadPreview").attr("src", src);
                    var xx = document.createElement('img');
                    $(xx).attr("src", src);
                    $(xx).attr("width","200px");
                    $(xx).attr("height","200px");

                    $("#uploadPreview").append(xx);
                }
            }
        });
    </script>
{%- endblock -%}